default['build-cookbook']['pmd']['path'] = "/opt/pmd"
#"http://liquidtelecom.dl.sourceforge.net/project/pmd/pmd/5.1.0/pmd-bin-5.1.0.zip"
default['build-cookbook']['s3']['bucket_name'] = "emea-techcft"
default['build-cookbook']['ssh_user'] = "ec2-user"
default['build-cookbook']['ssh_key_path'] = "/var/opt/delivery/workspace/.ssh/user.pem"
