name 'spring-petclinic-new-app-deploy'
maintainer 'EMEA Tech CFT'
maintainer_email 'emea-techcft+delivery@chef.io'
license 'all_rights'
description 'Deploys a java app'
long_description 'A simple cookbook to deploy a java app'
version '0.2.6'

depends 'tomcat', '~> 2.3.1'
depends 'java', '~> 1.39.0'
